[project]
name = "worker"
version = "0.1.0"
description = "Worker service to process jobs"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.34.0",
    "pandas>=2.2.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
