[project]
name = "file-loader"
version = "0.1.0"
description = "Service to Load dynamoDB dim tables from S3 files uploads"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.34.0",
    "requests>=2.31.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
